spring.application.name=distributed-expense-splitter

spring.security.user.name=myuser
spring.security.user.password=mypassword



# Logging configuration
logging.level.root=info
logging.level.com.fairshare.distributed_expense_splitter=debug
logging.file.name=logs/expense-splitter.log
logging.pattern.console=%clr(%d{yyyy-MM-dd HH:mm:ss}){faint} %clr([%-5level]) %clr(- %logger{36}){cyan} - %msg%n

logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%-5level] - %logger{36} - %msg%n








# H2 Database configuration
# spring.datasource.url=jdbc:h2:mem:expensesdb
# spring.datasource.driverClassName=org.h2.Driver
# spring.datasource.username=user
# spring.datasource.password=pass

# JPA configuration
# spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
# spring.jpa.hibernate.ddl-auto=update
# spring.jpa.show-sql=true

# Enable H2 Web Console to view your tables in the browser
# spring.h2.console.enabled=true
# spring.h2.console.path=/h2-console



# PostgreSQL Database Connection Settings
spring.datasource.url=jdbc:postgresql://localhost:5432/fairshareDB
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Configurations
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# Optional: Show SQL queries in the console for easy debugging
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true






# Logs/Messages
success.operation.completed=Operation completed successfully.
success.resource.created=Resource created successfully.
success.resource.updated=Resource updated successfully.
success.resource.deleted=Resource deleted successfully.

error.unexpected=An unexpected error occurred.
error.internal.server=Internal server error.
error.invalid.request=Invalid request.
error.validation.failed=Validation failed.

used.create.request=user creation request received for email {}.
user.created=User created successfully.
user.updated=User updated successfully.
user.deleted=User deleted successfully.

error.user.not.found=User not found with id {}.
error.user.email.exists=User already exists with email {}.
error.user.invalid.id=Invalid user id {}.
error.user.required.name=User name is required.
error.user.required.email=User email is required.

# GROUPS
group.created=Group created successfully.
group.updated=Group updated successfully.
group.deleted=Group deleted successfully.

error.group.not.found=Group not found with id {}.
error.group.already.exists=Group already exists with name {}.
error.group.required.name=Group name is required.
error.group.invalid.id=Invalid group id {}.

# MEMBERS

member.added=Member added successfully.
member.removed=Member removed successfully.

error.member.already.exists=User {} is already a member of group {1}.
error.member.not.found=User {} is not a member of group {1}.


# EXPENSES
expense.created=Expense created successfully.
expense.updated=Expense updated successfully.
expense.deleted=Expense deleted successfully.

error.expense.not.found=Expense not found with id {}.
error.expense.invalid.amount=Expense amount must be greater than zero.
error.expense.invalid.paidBy=PaidBy user is invalid.
error.expense.invalid.group=Group does not exist.
error.expense.split.invalid=Expense split amount is invalid.

# BALANCES

balance.calculated=Balances calculated successfully.
error.balance.calculation.failed=Failed to calculate balances.