openapi: 3.0.3
info:
  title: Expense Splitter API
  version: 1.0.0

servers:
  - url: http://localhost:8080


paths:
  /welcome:
    get:
      tags:
        - Welcome
      summary: Welcome endpoint
      description: Returns a welcome message.
      operationId: getWelcomeMessage

      responses:
        '200':
          description: Welcome message

          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WelcomeResponse'
  /users:
    post:
      summary: Create User
      operationId: createUser

      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateUserRequest'

      responses:
        '201':
          description: User Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserDTO'

    get:
      summary: Get All Users
      operationId: getUsers

      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/UserDTO'

  /users/{userId}:
    get:
      summary: Get User
      operationId: getUser

      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: integer
            format: int64

      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserDTO'


  /groups/{groupId}/members:

    post:
      summary: Add Member

      operationId: addMember

      parameters:
        - name: groupId
          in: path
          required: true
          schema:
            type: integer
            format: int64

      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AddMemberRequest'

      responses:
        '204':
          description: Added

  /expenses:

    post:
      summary: Create Expense

      operationId: createExpense

      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateExpenseRequest'

      responses:
        '201':
          description: Created


components:

  schemas:

    UserDTO:
      type: object
      properties:
        id:
          type: integer
          format: int64

        name:
          type: string

        email:
          type: string

    CreateUserRequest:
      type: object

      required:
        - name
        - email

      properties:
        name:
          type: string

        email:
          type: string

    GroupDTO:
      type: object

      properties:
        id:
          type: integer
          format: int64

        name:
          type: string

        description:
          type: string

    CreateGroupRequest:
      type: object

      required:
        - name

      properties:
        name:
          type: string

        description:
          type: string

    AddMemberRequest:
      type: object

      required:
        - userId

      properties:
        userId:
          type: integer
          format: int64

    CreateExpenseRequest:
      type: object

      required:
        - groupId
        - paidBy
        - amount

      properties:
        groupId:
          type: integer
          format: int64

        paidBy:
          type: integer
          format: int64

        description:
          type: string

        amount:
          type: number
          format: double

    WelcomeResponse:
      type: object

      properties:
        message:
          type: string
          example: Welcome to Expense Splitter API